---
site_name: Em Like the Dash
docs_dir: docs
exclude_docs: |
  projects.md
  talks.md
  personal.md
  skills.md
  caddy-on-gcp.md
theme:
  name: material
  font:
    text: Inter
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette: 
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Light Mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Dark Mode
  features:
    - navigation.footer
    - search.suggest
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - blog:
      authors: false
      blog_toc: true
      blog_categories: true
      blog_tags: true
      blog_nav: true
  - privacy
repo_url: https://github.com/microcosem
nav:
  - Welcome: 'index.md'
  - Blog: 'blog/index.md'
  - Resume: 'resume.md'
  # - Projects: 'projects.md'
  # - Talks: 'talks.md'
  # - Writing: 'personal.md'
  # - Professional:
  # - Toolbox: 'skills.md'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/microcosem
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/em-h-2b80992b3/
extra_css:
  - static/extras.css