---
site_name: Em Like the Dash
docs_dir: docs
theme:
  name: material
  font:
    text: Inter
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette: 
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Light Mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-night
        name: Dark Mode
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - blog:
      authors: false
  - privacy
repo_url: https://github.com/microcosem
nav:
  - Home: 'index.md'
  - Résumé: 'resume.md'
  - 'Portfolio':
    - Professional: 'professional.md'
    - Independent: 'personal.md'
